# fly.toml app configuration file generated for scott-cf-test on 2023-10-29T14:26:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scott-cf-test"
primary_region = "lhr"

[build]

[http_service]
internal_port = 8888
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
